fix: GH workflow add inputs parameters

diff --git a/.github/workflows/api-tests-dispatch.yml b/.github/workflows/api-tests-dispatch.yml
--- a/.github/workflows/api-tests-dispatch.yml
+++ b/.github/workflows/api-tests-dispatch.yml
@@ -3,15 +3,68 @@ name: MyPlace Postman Tests Dispatch
 on:
   workflow_dispatch:
     inputs:
-      deployment-targets:
-        description: "Choose targets for Postman tests (comma-separated, e.g., stats-tests,security-tests). 
-                      All items:
-                       - stats-tests
-                       - security-tests
-                       - profile-tests
-                       - develop-tests"
+
+      # Project build parameters
+      build-profiles:
+        description: |
+          Choose Maven profiles for building the project (comma-separated, e.g., check,coverage).
+          Examples:
+           - check:    Run code style checks.
+           - coverage: Check and generate reports for tests coverage.
+          Default: none.
+        required: false
+        default: ""
+        type: string
+
+      build-skip-tests:
+        description: |
+          Skip running tests during the build.
+          If true, the build will run with `-Dmaven.test.skip=true` (not with `-DskipTests`).
+          If false, tests will be executed.
+          Default: false.
+        required: false
+        default: false
+        type: boolean
+
+      # Parameters for running Postman tests
+      environment:
+        description: |
+          Choose the environment for Postman tests.
+          This will determine which docker-compose file is used:
+           - prod: Use docker-compose-prod.yml.
+           - dev:  Use docker-compose-dev.yml.
+           - test: Use docker-compose-test.yml.
+          Default: test.
         required: true
-        default: "develop-tests"
+        default: "test"
+        type: choice
+        options:
+          - prod
+          - dev
+          - test
+
+      additional-spring-profiles:
+        description: |
+          Choose additional Spring profiles (comma-separated, e.g., test-mail-sender-bypassing,test-confirmation-code-reading).
+          Available profiles:
+           - test-mail-sender-bypassing:     Bypass email sending.
+           - test-confirmation-code-reading: Enable the reading of confirmation codes by responding to API requests.
+          Default: none.
+        required: false
+        default: ""
+        type: string
+
+      deployment-targets:
+        description: |
+          Choose targets for Postman tests (comma-separated, e.g., stats-tests,security-tests).
+          Available targets:
+           - stats-tests:    Run statistics-related tests.
+           - security-tests: Run security-related tests.
+           - profile-tests:  Run profile-related tests.
+           - all-tests:      Run all tests.
+          Default: all-tests.
+        required: true
+        default: "all-tests"
         type: string
 
 jobs:
@@ -23,9 +76,6 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
-
-#      - name: List directory structure
-#        run: ls -R
 
       - name: Set up Docker
         uses: docker/setup-docker-action@v3
@@ -67,8 +117,6 @@ jobs:
           sudo apt-get install -y postgresql postgresql-contrib
           sudo systemctl start postgresql
           sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '12345';"
-#          sudo -u postgres psql -c "CREATE USER user WITH PASSWORD '12345';"
-#          sudo -u postgres psql -c "CREATE DATABASE testdb OWNER user;"
 
       - name: Install Docker Compose
         run: |
@@ -91,21 +139,85 @@ jobs:
         run: pg_isready -h localhost -p 5432
 
       - name: Build Java project
-        run: mvn clean package
+        run: |
+          MAVEN_PROFILES=${{ github.event.inputs.build-profiles }}
+          MAVEN_PROFILES_OPTION=""
+          if [ -n "$MAVEN_PROFILES" ]; then
+            MAVEN_PROFILES_OPTION="-P$MAVEN_PROFILES"
+          fi
+          
+          SKIP_TESTS_FLAG=""
+          if ${{ github.event.inputs.build-skip-tests }}; then
+            SKIP_TESTS_FLAG="-Dmaven.test.skip=true"
+          fi
+          
+          echo "COMMAND: mvn clean package -B -P$MAVEN_PROFILES $SKIP_TESTS_FLAG"
+          mvn clean package -B $MAVEN_PROFILES_OPTION $SKIP_TESTS_FLAG
 
-#      - name: Check for jar files
-#        run: ls -la mp-security/target/
+      - name: Set up Docker Compose file
+        working-directory: ./docker
+        run: |
+          COMPOSE_FILE=docker-compose-${{ github.event.inputs.environment }}.yml
+          if [ ! -f "$COMPOSE_FILE" ]; then
+            echo "file not found: $COMPOSE_FILE"
+            exit 1
+          fi
+          echo "COMPOSE_FILE=$COMPOSE_FILE" >> $GITHUB_ENV
+          echo "Docker Compose file set to: $COMPOSE_FILE"
+
+      - name: Set up Spring profiles option
+        id: set-spring-profiles-option
+        run: |
+          ADDITIONAL_SPRING_PROFILES="${{ github.event.inputs.additional-spring-profiles }}"    
+          
+          if [ -n "$ADDITIONAL_SPRING_PROFILES" ]; then
+            BASE_PROFILE=""          
+          
+            case ${{ github.event.inputs.environment }} in
+              test)
+                BASE_PROFILE="test"
+                ;;
+              dev)
+                BASE_PROFILE="develop"
+                ;;
+              prod)
+                BASE_PROFILE="production"
+                ;;
+              *)
+                echo "No matches for the environment: ${{ github.event.inputs.environment }}". 
+                exit 1
+                ;;
+            esac        
+          
+            SPRING_PROFILES_OPTION="SPRING_PROFILES_ACTIVE=$BASE_PROFILE,$ADDITIONAL_SPRING_PROFILES"
+            echo "SPRING_PROFILES_OPTION=$SPRING_PROFILES_OPTION" >> $GITHUB_OUTPUT
+            echo "Spring profiles option set to: $SPRING_PROFILES_OPTION" # TODO: not recipe value from $SPRING_PROFILES_OPTION
+          else
+            echo "SPRING_PROFILES_OPTION=" >> $GITHUB_OUTPUT
+            echo "No additional Spring profiles provided."
+          fi
 
       - name: Build project images
         working-directory: ./docker
-        run: docker-compose -f docker-compose-dev.yml --profile full build
+        run: |
+          echo "COMMAND docker-compose -f $COMPOSE_FILE --profile full build"
+          docker-compose -f $COMPOSE_FILE --profile full  build
 
       - name: Run project
         working-directory: ./docker
-        run: docker-compose -f docker-compose-dev.yml --profile full up -d
+        run: |
+          SPRING_PROFILES_OPTION=${{ steps.set-spring-profiles-option.outputs.SPRING_PROFILES_OPTION }}
+          
+          if [ -n "$SPRING_PROFILES_OPTION" ]; then
+            echo "COMMAND export $SPRING_PROFILES_OPTION"
+            export "$SPRING_PROFILES_OPTION"
+          fi
+          
+          echo "COMMAND docker-compose -f $COMPOSE_FILE --profile full up -d"
+          docker-compose -f $COMPOSE_FILE --profile full up -d
 
       - name: Check Docker containers
-        run: docker ps
+        run: docker ps -a
 
       - name: Cache Node.js modules
         id: cache-node-modules
@@ -136,8 +248,8 @@ jobs:
             elif [ "$target" == "profile-tests" ]; then
               echo "Running profile-tests"
               newman run postman/MyPlace-mp-profile.postman_collection.json --reporters junit --reporter-junit-export postman-profile-report.xml --disable-unicode --verbose
-            elif [ "$target" == "develop-tests" ]; then
-              echo "Running develop-tests"
+            elif [ "$target" == "all-tests" ]; then
+              echo "Running all-tests"
               newman run postman/MyPlace-mp-profile.postman_collection.json --reporters junit --reporter-junit-export postman-profile-report.xml
               newman run postman/MyPlace-mp-security.postman_collection.json --reporters junit --reporter-junit-export postman-security-report.xml
               newman run postman/MyPlace-mp-stats.postman_collection.json --reporters junit --reporter-junit-export postman-stats-report.xml
